### ISSUE TITLE
Issue deploying

### ISSUE THREAD

**Issue by mmeisels** [gonimbly/engager-api#3]
There is an issue with the deploy.

It looks like in the db script that the picture field is being added twice. Once in the create table statement and again later.

**Comment by mmeisels** [comment]
Postgres tables successfully initialized
Knex:warning - migrations failed with error: alter table "users" add column "picture_url" text default 'https://randomuser.me/api/portraits/med/women/17.jpg' - column "picture_url" of relation "users" already exists
Error migrating Postgres
{ [error: alter table "users" add column "picture_url" text default 'https://randomuser.me/api/portraits/med/women/17.jpg' - column "picture_url" of relation "users" already exists]
  name: 'error',
  length: 128,
  severity: 'ERROR',
  code: '42701',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '4845',
  routine: 'check_for_column_name_collision' }

**Comment by troyconquer** [comment]
Thanks for reporting. We're working through some changes right now. Well try to have a fix for you sometime tomorrow.

**Comment by troyconquer** [comment]
Hi there @mmeisels , so we are in the middle of merging our two repos, engager-api / engager-ui.  Right now github.com/gonimbly/engager-ui is working correctly with the merge. My intention is to have a gonimbly/engager-app in the future.

We just wanted to make it easier to manage and start to eliminate any unnecessary code moving forward.

https://github.com/gonimbly/engager-ui is ready for deployment via  Heroku button.

Let us know if you see anything else.

Troy
